### ISSUE TITLE
Problems with entering links in CKEditor

### ISSUE THREAD

**Issue by robo-wg** [teppokoivula/AdminBar#5]
Hello and thanks for this great module.
When I try to insert a link under Edit in CKEditor the window for entering links doesn´t appear in FF an Chrome. 
I find the following error in the console: TypeError: parent.jQuery is not a functionmodal.js:112:12
Best Regards
Robert

**Comment by teppokoivula** [comment]
Hey @robo-wg. This should be fixed now with the latest version, 2.4.1. Please let me know if the issue persists, though!
