### ISSUE TITLE
create new page not working when template has repeater matrix field

### ISSUE THREAD

**Issue by jploch** [teppokoivula/AdminBar#6]
I found a bug when using this module on a page with a repeater matrix field.
After adding a new page from the adminbar, the module redirects to the repeater page that lives under admin->repeaters->repeater-field-name->page instead of the real parent page. A message is shown "This page has no process assigned". However the page gets created under the correct parent page. So just the redirect is wrong. This only happens with the modal option.

**Comment by teppokoivula** [comment]
@jploch, any chance you could test if 2.6.2 finally fixes this issue? :)

**Comment by teppokoivula** [comment]
This appears to be fixed so I'm closing the issue, but please let me know if the problem still persists.
