### ISSUE TITLE
image path to pw-mark.png

### ISSUE THREAD

**Issue by esszett** [teppokoivula/AdminBar#8]
Hello Teppo,

the option for displaying the pwire logo is broken – it seems the path uikit/custom/images/ doesn't exists anymore in pwire 3.0.210, instead i found uikit-pw/images/ 
https://github.com/processwire/processwire/tree/master/wire/modules/AdminTheme/AdminThemeUikit/uikit

theme.php L73
// ProcessWire logo/mark/icon.
    $theme_path = $this->config->paths->AdminThemeUikit;
    if ($theme_path) {
        //$img = 'uikit/custom/images/pw-mark.png';
        $img = 'uikit-pw/images/pw-mark.png';

**Comment by teppokoivula** [comment]
Thanks @esszett, this is now fixed :)
